spring:
  application:
    name: jwkms

server:
  hostname: localhost
  port: 8443
  ssl:
    enabled: true
    client-auth: WANT
    trust-store: classpath:keystores/truststore.jks
    trust-store-password: changeit
    key-store: classpath:keystores/keystore.jks
    key-store-password: changeit
    key-password: ${server.ssl.key-store-password}
    client-certs-key-alias: ${server.hostname}

#JKWMS configuration
jwkms:
  root: https://${server.hostname}:${server.port}
  certificateAuthorityAlias: obri-external-ca
  tan: example.com
  certificate:
    ou: forgerock.financial
    o: ForgeRock
    l: Bristol
    st: Avon
    c: UK
  jwkMsId: jwkms
  rotationScheduler: "0 0 1 * * *"
  keysCleanup: "0 0 1 * * *"
  transport:
    algorithm: PS256
  signing:
    algorithm: PS256
  encryption:
    algorithm: RSA-OAEP-256
  encryptionMethod: A128CBC_HS256
  ExpirationWindowInMillis: 7200
  rotation:
    transport: 7776000000
    keys: 7776000000
  jwk-key-store: classpath:keystores/jwksstore.pfx
  jwk-key-store-password: changeit
  forgerock-applications:
    #Group your micro-services so they use the same set of keys.
    - name: aspsp
      group: as.aspsp.${dns.hosts.root}, rs.aspsp.${dns.hosts.root}, rcs.aspsp.${dns.hosts.root}, simulator.rs.${dns.hosts.root}, service.bank.${dns.hosts.root}, rs-store.aspsp.${dns.hosts.root}

#Metrics configuration
metrics:
  endpoints:
    root: https://metrics-services:8444
    endpoint-usage:
      add-entries: ${metrics.endpoints.root}/api/kpi/endpoint-usage/add-entries
    jwts-generation:
      add-entries: ${metrics.endpoints.root}/api/kpi/jwts/jwts-generation/add-entries
    jwts-validation:
      add-entries: ${metrics.endpoints.root}/api/kpi/jwts/jwts-validation/add-entries
#Swagger
swagger:
  license: "open-licence"
  license-url: "https://www.openbanking.org.uk/open-licence"
  terms-of-service-url: "https://backstage.forgerock.com/knowledge/openbanking/article/a45894685"
  version: "v3.1.1"
  contact:
    name: "ForgeRock AS"
    url: "https://${server.hostname}"
    email: "openbanking-support@forgerock.com"
  title: "JWK Management Services APIs Specification"
  description: "Swagger for JWK management services APIs Specification"
